# NAME: VAISHNAVI PASWAN
# BATCH: B1
# ROLL NO: 13
# AIM: TO IMPLEMENT NAIVE BAYES ALGORITHM.

In [62]:
import pandas as pd

In [64]:
df=pd.read_csv("play_tennis.csv")
df

    day   outlook  temp humidity    wind play
0    D1     Sunny   Hot     High    Weak   No
1    D2     Sunny   Hot     High  Strong   No
2    D3  Overcast   Hot     High    Weak  Yes
3    D4      Rain  Mild     High    Weak  Yes
4    D5      Rain  Cool   Normal    Weak  Yes
5    D6      Rain  Cool   Normal  Strong   No
6    D7  Overcast  Cool   Normal  Strong  Yes
7    D8     Sunny  Mild     High    Weak   No
8    D9     Sunny  Cool   Normal    Weak  Yes
9   D10      Rain  Mild   Normal    Weak  Yes
10  D11     Sunny  Mild   Normal  Strong  Yes
11  D12  Overcast  Mild     High  Strong  Yes
12  D13  Overcast   Hot   Normal    Weak  Yes
13  D14      Rain  Mild     High  Strong   No

In [66]:
target = df['play']
attributes = df.drop(columns=['day', 'play'])

In [68]:
def prior(target,label):
    return sum(target==label)/len(target)

In [70]:
def conditional(feature,value,target,label):
    count_label=sum(target==label)
    count_feature=sum((target==label)&(feature==value))
    if(count_label>0):
        return count_feature/count_label
    else:
        return 0

In [88]:
def posterior(test):
    classes=['Yes','No']
    posteriors=[]
    for label in classes:
        prior_prob=prior(target,label)
        prob=prior_prob
        for feature_name in attributes.columns:
            prob*=conditional(df[feature_name],test[feature_name],target,label)
        print(f"Posterior probability for class '{label}':{prob}")
        posteriors.append(prob)
    return posteriors

In [116]:
test={'outlook':'Sunny','temp':'Cool','humidity':'High','wind':'Strong'}

In [140]:
classes=['Yes','No']
for label in classes:
    prior_probabilities = prior(target, label)
    print(f"Prior probability for class '{label}':{prior_probabilities}")

Prior probability for class 'Yes':0.6428571428571429
Prior probability for class 'No':0.35714285714285715

In [138]:
for label in classes:
    print(f"Conditional probabilities for class '{label}':")
    for feature_name in attributes.columns:
            conditional_probabilities=conditional(df[feature_name], test_instance[feature_name], target, label)
            print(f"  P({feature_name} = {test_instance[feature_name]} | class = {label}): {conditional_probabilities}")

Conditional probabilities for class 'Yes':
  P(outlook = Sunny | class = Yes): 0.2222222222222222
  P(temp = Cool | class = Yes): 0.3333333333333333
  P(humidity = High | class = Yes): 0.3333333333333333
  P(wind = Strong | class = Yes): 0.3333333333333333
Conditional probabilities for class 'No':
  P(outlook = Sunny | class = No): 0.6
  P(temp = Cool | class = No): 0.2
  P(humidity = High | class = No): 0.8
  P(wind = Strong | class = No): 0.6

In [122]:
posterior_probabilities=posterior(test)

Posterior probability for class 'Yes':0.005291005291005291
Posterior probability for class 'No':0.02057142857142857

In [160]:
for i in range(len(classes)):
    label=classes[i]
    p=posterior_probabilities[i]
    print(f"Normalized posterior probabilities for class '{label}': {p/sum(posterior_probabilities)}")

Normalized posterior probabilities for class 'Yes': 0.20458265139116202
Normalized posterior probabilities for class 'No': 0.795417348608838

In [124]:
classes=['Yes','No']
prediction= classes[posterior_probabilities.index(max(posterior_probabilities))]

In [126]:
print("Predicted Class of ",test,"is",prediction)

Predicted Class of  {'outlook': 'Sunny', 'temp': 'Cool', 'humidity': 'High', 'wind': 'Strong'} is No

In [174]:
import warnings
warnings.filterwarnings("ignore")
import numpy as np
from sklearn.naive_bayes import GaussianNB

In [180]:
df=pd.read_csv("nv_dataset.csv")
df

    FRUIT  WEIGHT(G)  COLOUR
0   APPLE        150     RED
1   APPLE        170     RED
2  ORANGE        160  ORANGE
3  ORANGE        180  ORANGE
4   APPLE        140     RED
5  ORANGE        175  ORANGE

In [224]:
target_col='FRUIT'
X=df.drop(columns=[target_col])
y=df[target_col]

In [226]:
X=pd.get_dummies(X)

In [261]:
gnb=GaussianNB()
gnb.fit(X,y)

GaussianNB()

In [263]:
test={"Weight":165,"COLOUR":'RED'}

In [267]:
test_df=pd.DataFrame([test])

In [269]:
new_fruit=pd.get_dummies(test_df).reindex(columns=X.columns, fill_value=0)

In [271]:
prediction = gnb.predict(new_fruit)

In [273]:
print("Predicted Class:", prediction[0])

Predicted Class: APPLE